#!/usr/bin/env fish
# Function to display all command abbreviations and aliases organized by category.
# Usage:
#   aliases_cheat_sheet

function aliases_cheat_sheet --description "Display all command abbreviations and aliases"
    echo ""
    echo "🔧 CONFIGURATION:"
    echo "  - efa              Edit fish config directory"
    echo "  - efc              Edit fish configuration"
    echo "  - eff              Edit fish functions"
    echo "  - egc              Edit .gitconfig"
    echo "  - kbcs             Show keyboard cheat sheet"
    echo "  - alcs             Show aliases cheat sheet"
    echo ""

    echo "🖥️  SYSTEM:"
    echo "  - ff               Show system info"
    echo "  - us               Update system"
    echo "  - cs               Clean system"
    echo "  - ks               Kill audio daemons"
    echo "  - des              Disable emulator audio"
    echo "  - ado              Enable 'AirDrop' to 'Everyone'"
    echo "  - adc              Disable 'AirDrop'"
    echo "  - po               Shutdown system"
    echo "  - zzz              Sleep system"
    echo ""

    echo "📦 PACKAGE MANAGEMENT:"
    echo "  - pi <pkg>         Install package"
    echo "  - pr <pkg>         Uninstall package"
    echo ""

    echo "🌐 NETWORK:"
    echo "  - wrip <port>      Show what's running on the specified port"
    echo "  - wpi <pid>        Show what's running with the specified process ID"
    echo "  - ip               Show IP address"
    echo ""

    echo "⌨️  TERMINAL TOOLS:"
    echo "  - ls               List files"
    echo "  - cat              View file"
    echo "  - cp               Copy file"
    echo "  - find             Find files"
    echo "  - sed              Stream edit"
    echo "  - mkdir            Create directory"
    echo "  - jsn              View JSON"
    echo "  - rmdp             Remove duplicates files"
    echo "  - dl <url>         Download file"
    echo "  - fm               Open TUI file manager"
    echo "  - oc               Open OpenCore CLI"
    echo "  - cl               Clear screen"
    echo "  - eva <expr>       Calculate expression"
    echo "  - cd <dir>         Change directory"
    echo "  - h                Show history"
    echo "  - hs               Search history"
    echo "  - hlx <file>       Edit file in TUI editor"
    echo "  - ct               Open SSH TUI manager"
    echo ""

    echo " GIT:"
    echo "  - gst              Status"
    echo "  - ga               Add changes"
    echo "  - gap              Patch changes"
    echo "  - gc               Commit"
    echo "  - gca              Amend commit"
    echo "  - gps              Push"
    echo "  - gpsf             Force push"
    echo "  - gpl              Pull"
    echo "  - gft              Fetch"
    echo "  - gftpl            Fetch & pull"
    echo "  - gl               Show log"
    echo "  - gls              Show branch log"
    echo "  - gd               Show diff"
    echo "  - gds              Show staged differences"
    echo "  - gdsn             Show staged differences names only"
    echo "  - gco              Checkout"
    echo "  - gcob             Create branch"
    echo "  - gbr              Manage branches"
    echo "  - gbrls            List branches"
    echo "  - gbrd             Delete branch"
    echo "  - gbrdf            Force delete branch"
    echo "  - gbrr             Rename branch"
    echo "  - grb              Interactive rebase"
    echo "  - grba             Abort rebase"
    echo "  - grbc             Continue rebase"
    echo "  - grbs             Skip in rebase"
    echo "  - gfrb             Fetch and rebase"
    echo "  - grstr            Restore files"
    echo "  - grstrs           Restore staged"
    echo "  - grstb            Reset to remote"
    echo "  - grst1            Undo last commit"
    echo "  - grstlb           Hard reset"
    echo "  - gcp              Cherry-pick"
    echo "  - gcpc             Cherry-pick interactive"
    echo "  - gcpa             Abort cherry-pick"
    echo "  - gsts             Create stash"
    echo "  - gstsl            List stashes"
    echo "  - gstsa            Apply stash"
    echo "  - gstsp            Pop stash"
    echo "  - gstsd            Delete stash"
    echo "  - gfx              Mark fixup"
    echo "  - gafx             Interactive fixup"
    echo "  - grp              Cleanup"
    echo "  - gm               Merge"
    echo "  - gmr              Revert merge"
    echo "  - grc              Revert commit"
    echo "  - gra              Abort revert"
    echo "  - gsu              Add upstream"
    echo "  - gbs              Lines of code per author"
    echo ""

    echo "🌳 GITHUB:"
    echo "  - ghprs            Show PR reviews"
    echo "  - ghoprs           Show open PRs"
    echo "  - ghcprs           Show closed PRs"
    echo "  - ghprc            Create PR"
    echo ""

    echo "🐳 DOCKER:"
    echo "  - dc               Run Docker compose"
    echo "  - dcu              Run Docker compose in detached mode"
    echo "  - dcd              Stop Docker compose"
    echo "  - de               Execute command in Docker compose service"
    echo "  - dcl              Clean Docker compose"
    echo ""

    echo "⚙️  SYSTEM SERVICES:"
    echo "  - sc               Service control"
    echo "  - scsts            List services"
    echo "  - sci              Inspect service"
    echo "  - scstr            Load service"
    echo "  - sce              Enable service"
    echo "  - scstp            Unload service"
    echo "  - scd              Disable service"
    echo "  - scrr             Restart service"
    echo ""
end
